### ISSUE TITLE
Use subprocess with stdout=subprocess.PIPE for Python < 3.7 compatibility

### ISSUE THREAD

**Issue by sbailliez** [benkehoe/aws-sso-credential-process#2]
The subprocess calls are making use of capture_output which is python >= 3.7, is there any interest in adding compatibility for  < 3.7 and use stdout=subprocess.PIPE instead ?

Based on https://docs.python.org/3/library/subprocess.html capture_output = True is functionaly equivalent to specify pipe for stdout and stderr, so it would lead to:

`subprocess.run(['aws', 'configure', 'get', f'profile.{args.profile}.{name}'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout`

Thank you!

**Comment by benkehoe** [comment]
I published v0.3.1 with support with <3.7 (had to remove all the f-strings 🙁)

**Comment by sbailliez** [comment]
Ah shoot, didn't notice this. Thanks for making this update, much appreciated ! 

We're trying to roll out aws sso usage and that's going to be really helpful. Thanks again for making that lib available.
